#!/usr/bin/env node
/**
 * Exports the service for mounting inside another Vercel project (static site plus one function).
 *
 *   node scripts/export-mount.mjs --out ../fire-dev-site [--prefix /connectors]
 *
 * Writes into the host repo:
 *   api/connectors.js               one bundled CommonJS Vercel Function (no host dependencies needed)
 *   public/connectors/**            landing, docs, privacy, terms, llms.txt, style, with links under --prefix
 *   connectors.rewrites.json        the vercel.json "rewrites" entries the host must contain
 *
 * The host sets CONNECTORS_* environment variables (see src/mounted.ts) and LANDING_PATH=<prefix>.
 */
import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};
const out = resolve(opt("out", ""));
if (!opt("out")) throw new Error("--out <host repo> is required");
const prefix = opt("prefix", "/connectors").replace(/\/+$/, "");
const sha = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: root }).toString().trim();

// 1. Function bundle.
const outFile = join(out, "api", "connectors.js");
mkdirSync(dirname(outFile), { recursive: true });
await build({
  entryPoints: [join(root, "src", "mounted.ts")],
  outfile: outFile,
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  minify: true,
  legalComments: "none",
  banner: { js: `/* Generated by meshvault-connectors scripts/export-mount.mjs from commit ${sha}. Do not edit; re-export instead. */` },
  footer: { js: "module.exports=module.exports.default;module.exports.config={api:{bodyParser:false}};" },
});

// 2. Static pages under the prefix.
const dest = join(out, "public", prefix.replace(/^\//, ""));
rmSync(dest, { recursive: true, force: true });
cpSync(join(root, "public"), dest, { recursive: true });
rmSync(join(dest, "robots.txt"));

const PAGES = "style\\.css|app\\.js|favicon\\.svg|docs|privacy|terms|llms\\.txt";
function rewrite(text, isHtml) {
  let t = text;
  if (isHtml) {
    t = t.replace(/(href|src)="\/#pricing"/g, `$1="${prefix}#pricing"`);
    t = t.replace(/(href|src)="\/"/g, `$1="${prefix}"`);
    t = t.replace(new RegExp(`(href|src)="/(${PAGES})"`, "g"), `$1="${prefix}/$2"`);
  } else {
    t = t.replace(new RegExp(`^(- (?:Docs|Privacy|Terms): )/(docs|privacy|terms)$`, "gm"), `$1${prefix}/$2`);
  }
  return t;
}
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(html|txt)$/.test(name)) writeFileSync(p, rewrite(readFileSync(p, "utf8"), name.endsWith(".html")));
  }
})(dest);

// 3. The rewrites the host's vercel.json needs: the service owns these public paths.
const fn = "/api/connectors";
const r = (source, rest) => ({ source, destination: `${fn}?__path=${rest ?? source}` });
writeFileSync(
  join(out, "connectors.rewrites.json"),
  JSON.stringify(
    [
      r("/mcp"),
      r("/mcp/try"),
      r("/health"),
      r("/oauth/:rest*"),
      r("/.well-known/oauth-protected-resource"),
      r("/.well-known/oauth-protected-resource/:rest*"),
      r("/.well-known/oauth-authorization-server"),
      r("/.well-known/openid-configuration"),
      r("/.well-known/mcp/:rest*"),
      r("/billing/:rest*"),
      r("/api/keys/:rest*"),
      r("/api/usage"),
      r("/api/checkout"),
      r("/api/billing/:rest*"),
      r("/api/stripe/:rest*"),
    ],
    null,
    2,
  ) + "\n",
);
console.log(`exported ${sha} to ${out} (prefix ${prefix})`);
